// ===== CONSULTORIA: PHASES & TASKS =====
const CONSULTORIA_PHASES = [
  {
    id: 1, name: 'Fundamentos & Setup', months: 'Mar-Abr 2026', icon: '🔧', color: '#3b82f6',
    tasks: [
      { id: 'c1_1', name: 'Abrir MEI (CNAE 7120-1/00 – testes e análises técnicas)', type: 'market', xp: 100 },
      { id: 'c1_2', name: 'Criar conta bancária PJ (Nubank PJ ou C6 Bank)', type: 'market', xp: 50 },
      { id: 'c1_3', name: 'Completar curso Python + Pandas (Kaggle Learn)', type: 'study', xp: 80 },
      { id: 'c1_4', name: 'Estudar Streamlit (docs oficiais + tutoriais)', type: 'study', xp: 60 },
      { id: 'c1_5', name: 'Mapear 50+ cervejarias de MG (SICOBE, Google Maps, Instagram)', type: 'project', xp: 100 },
      { id: 'c1_6', name: 'Mapear 30+ usinas sucroalcooleiras (UNICA, Sindalcool-MG, CONAB)', type: 'project', xp: 100 },
    ]
  },
  {
    id: 2, name: 'Projeto Demonstração', months: 'Abr-Mai 2026', icon: '📊', color: '#f59e0b',
    tasks: [
      { id: 'c2_1', name: 'Coletar dados públicos (EPE, PROCEL, CEMIG) em CSV limpo', type: 'project', xp: 60 },
      { id: 'c2_2', name: 'Definir benchmarks e montar lógica de cálculo em Python', type: 'tool', xp: 80 },
      { id: 'c2_3', name: 'Construir Dashboard de Benchmark Energético no Streamlit', type: 'tool', xp: 250 },
      { id: 'c2_4', name: 'Integrar API Claude para geração automática de relatório', type: 'tool', xp: 150 },
      { id: 'c2_5', name: 'Deploy no Streamlit Cloud + README no GitHub', type: 'deliverable', xp: 100 },
      { id: 'c2_6', name: 'Escrever e publicar artigo técnico no LinkedIn/Medium', type: 'market', xp: 120 },
    ]
  },
  {
    id: 3, name: 'Primeiras Abordagens', months: 'Mai-Jun 2026', icon: '🎯', color: '#8b5cf6',
    tasks: [
      { id: 'c3_1', name: 'Conversar com 3 professores UFMG (pedir indicações)', type: 'market', xp: 80 },
      { id: 'c3_2', name: 'LinkedIn: conectar com 100 donos/gerentes de cervejarias e usinas', type: 'market', xp: 100 },
      { id: 'c3_3', name: 'Enviar 20 cold e-mails usando script do plano', type: 'market', xp: 120 },
      { id: 'c3_4', name: 'Participar de 1 evento de cervejarias artesanais em MG', type: 'market', xp: 100 },
      { id: 'c3_5', name: 'Oferecer diagnóstico gratuito para 3 cervejarias locais', type: 'market', xp: 150 },
      { id: 'c3_6', name: 'Criar site provisório (Notion/Carrd) com portfólio e contato', type: 'deliverable', xp: 80 },
      { id: 'c3_7', name: 'Completar Checklist de Saída da Faculdade (todos os 8 itens)', type: 'deliverable', xp: 200 },
    ]
  },
  {
    id: 4, name: 'Outreach Intensivo', months: 'Jul 2026 (Sem 1-4)', icon: '📞', color: '#ef4444',
    tasks: [
      { id: 'c4_1', name: 'Rotina: enviar 10 cold e-mails toda segunda-feira', type: 'market', xp: 80 },
      { id: 'c4_2', name: 'Rotina: fazer 5 ligações telefônicas toda terça', type: 'market', xp: 80 },
      { id: 'c4_3', name: 'Rotina: posts técnicos + 20 conexões toda quarta no LinkedIn', type: 'market', xp: 60 },
      { id: 'c4_4', name: 'Rotina: follow-up de todos sem resposta toda quinta', type: 'market', xp: 60 },
      { id: 'c4_5', name: 'Rotina: 2 visitas presenciais a cervejarias toda sexta', type: 'market', xp: 100 },
      { id: 'c4_6', name: 'Conseguir 1 cervejaria interessada em diagnóstico gratuito', type: 'scenario', xp: 300 },
      { id: 'c4_7', name: 'Visitar presencialmente e coletar 12 meses de contas de energia', type: 'project', xp: 200 },
    ]
  },
  {
    id: 5, name: 'Diagnóstico & Proposta', months: 'Ago 2026 (Sem 5-8)', icon: '📋', color: '#10b981',
    tasks: [
      { id: 'c5_1', name: 'Analisar dados: consumo atual vs. benchmark do setor', type: 'project', xp: 150 },
      { id: 'c5_2', name: 'Identificar 3 oportunidades de redução ranqueadas por ROI', type: 'project', xp: 150 },
      { id: 'c5_3', name: 'Construir relatório profissional com dashboard interativo', type: 'deliverable', xp: 250 },
      { id: 'c5_4', name: 'Apresentar pessoalmente ao cliente (NÃO enviar por e-mail)', type: 'market', xp: 200 },
      { id: 'c5_5', name: 'Oferecer projeto pago de implementação da oportunidade #1', type: 'market', xp: 200 },
      { id: 'c5_6', name: 'Se não converteu: pivotar para padaria/laticínio/frigorífico', type: 'scenario', xp: 100 },
    ]
  },
  {
    id: 6, name: 'Escala & Recorrência', months: 'Set-Dez 2026+', icon: '🚀', color: '#f43f5e',
    tasks: [
      { id: 'c6_1', name: 'Fechar primeiro projeto pago (qualquer valor)', type: 'market', xp: 500 },
      { id: 'c6_2', name: 'Documentar case study completo do primeiro projeto', type: 'deliverable', xp: 200 },
      { id: 'c6_3', name: 'Pedir depoimento escrito do primeiro cliente', type: 'market', xp: 100 },
      { id: 'c6_4', name: 'Atingir R$ 5.000/mês de receita', type: 'market', xp: 400 },
      { id: 'c6_5', name: 'Criar pacote de monitoramento recorrente (R$ 800-2.000/mês)', type: 'deliverable', xp: 200 },
      { id: 'c6_6', name: 'Ter 3+ clientes ativos simultaneamente', type: 'market', xp: 300 },
      { id: 'c6_7', name: 'Atingir R$ 10.000/mês de receita por 3 meses consecutivos', type: 'market', xp: 500 },
    ]
  }
];

// ===== CONSULTORIA: TASK DETAILS =====
const CONSULTORIA_TASK_DETAILS = {
  c1_1: { title: '💼 Abrir MEI', what: 'Formalizar sua atuação como consultor. MEI permite emitir nota fiscal e ter CNPJ ativo imediatamente, sem precisar de CREA.', todo: ['Acessar o Portal do Empreendedor (gov.br/mei)', 'CNAE: 7120-1/00 – Testes e análises técnicas', 'Gerar CCMEI (Certificado de Condição de Microempreendedor)', 'Custo mensal: R$ 75 (DAS-MEI)', 'Não precisa do diploma para abrir — pode abrir AGORA'], resources: 'Portal do Empreendedor: gov.br/mei', criteria: 'CNPJ ativo e conta PJ operacional.' },
  c1_2: { title: '🏦 Conta Bancária PJ', what: 'Separar finanças pessoais de profissionais desde o dia 1.', todo: ['Abrir conta PJ no Nubank PJ, C6 Bank PJ ou Inter PJ (todas sem taxa)', 'Vincular ao CNPJ do MEI', 'Configurar como conta principal para receber de clientes'], resources: 'Nubank PJ, C6 Bank PJ, Banco Inter PJ', criteria: 'Conta PJ ativa e separada da conta pessoal.' },
  c1_3: { title: '📖 Python + Pandas', what: 'Aprender a linguagem base para análise de dados energéticos e construção de dashboards.', todo: ['Kaggle Learn: Intro to Python (6h)', 'Kaggle Learn: Pandas (4h)', 'Kaggle Learn: Data Manipulation (4h)', 'Criar 3 notebooks no GitHub com exercícios resolvidos', 'Praticar com dados reais: carregar CSV de consumo energético e fazer análise exploratória'], resources: 'kaggle.com/learn — cursos gratuitos e interativos', criteria: 'Certificado Kaggle + 3 notebooks limpos e documentados no GitHub.' },
  c1_4: { title: '📖 Streamlit', what: 'Aprender a construir dashboards web interativos sem conhecimento de frontend.', todo: ['Ler docs oficiais: docs.streamlit.io (tutorial de 30 min)', 'Assistir 2 tutoriais no YouTube sobre Streamlit', 'Construir um app demo simples rodando local com gráficos', 'Explorar a gallery de exemplos do Streamlit'], resources: 'docs.streamlit.io, Streamlit Gallery, YouTube tutorials', criteria: 'App demo Streamlit rodando local com inputs e gráficos interativos.' },
  c1_5: { title: '🗺️ Mapear Cervejarias de MG', what: 'Construir planilha de prospects com dados de contato de cervejarias artesanais de Minas Gerais.', todo: ['Google Maps: buscar "cervejaria artesanal" em BH, Contagem, Betim, Nova Lima, Sabará', 'Instagram: hashtags #cervejamineira #cervejaartesanalbh (perfis com 1k-10k seguidores)', 'SICOBE/MAPA: base oficial de cervejarias registradas em MG', 'Para cada: anotar nome, telefone, e-mail, Instagram, tamanho estimado', 'Organizar em Google Sheets com colunas: nome, contato, canal, status, próximo passo'], resources: 'Google Maps, Instagram, SICOBE/MAPA, Google Sheets', criteria: 'Planilha com 50+ cervejarias com dados de contato completos.' },
  c1_6: { title: '🗺️ Mapear Usinas Sucroalcooleiras', what: 'Identificar usinas de pequeno e médio porte no raio de 500km de BH.', todo: ['Sindalcool-MG: lista de associados (15-20 usinas)', 'UNICA: dados públicos de usinas cadastradas', 'CONAB: dados de produção por região', 'Focar em usinas de pequeno/médio porte (mais receptivas)', 'Lembrar: safra é abril-novembro em MG, timing é importante'], resources: 'Sindalcool-MG, UNICA, CONAB', criteria: 'Planilha com 30+ usinas com contatos e dados de porte.' },
  c2_1: { title: '📊 Coleta de Dados Públicos', what: 'Montar base de dados para alimentar o dashboard de benchmark.', todo: ['EPE (Balanço Energético Nacional): consumo por setor industrial', 'PROCEL/Eletrobras: benchmarks de eficiência para refrigeração, caldeiras, sistemas motrizes', 'CONAB: dados de produção sucroalcooleira por região', 'CEMIG: tarifas vigentes Grupo A e B em MG', 'Brewers Association (EUA): benchmarks kWh/bbl para cervejarias', 'Organizar tudo em CSVs limpos e documentados'], resources: 'epe.gov.br, procelinfo.com.br, conab.gov.br, cemig.com.br, brewersassociation.org', criteria: 'CSVs limpos com dados de benchmark prontos para uso no dashboard.' },
  c2_2: { title: '🧮 Lógica de Cálculo', what: 'Programar os cálculos de eficiência energética em Python.', todo: ['Consumo específico: kWh/litro produzido (cervejaria) ou kWh/tc (usina)', 'Benchmarks: cervejaria eficiente 8-12 kWh/hl, média 15-25 kWh/hl', 'Comparação percentual: (seu consumo - benchmark) / benchmark', 'Estimativa de economia: (excesso) × tarifa CEMIG × 12 meses', 'Ranking de oportunidades por ROI estimado', 'Testar com dados simulados em Jupyter Notebook'], resources: 'Python, Jupyter, dados coletados na tarefa anterior', criteria: 'Script Python testado que calcula eficiência e gera ranking de oportunidades.' },
  c2_3: { title: '🤖 Dashboard de Benchmark Energético', what: 'O projeto mais importante antes de falar com qualquer cliente. Prova que você sabe fazer o trabalho.', todo: ['Input do usuário: produção mensal (litros), tipo de equipamento (checkboxes), consumo kWh/mês, custo R$/mês', 'Cálculo automático: consumo específico, comparação com benchmark', 'Output: gráfico de barras comparativo, 3 maiores desperdícios, estimativa economia R$/ano', 'UI limpa e profissional — o cervejeiro tem que entender', 'Testar com pelo menos 3 cenários diferentes', 'Prospect acessa e testa com seus próprios dados — isso é o que convence'], resources: 'Streamlit, Plotly, dados de benchmark coletados', criteria: 'Dashboard funcional no Streamlit Cloud que qualquer cervejeiro consiga usar.' },
  c2_4: { title: '🤖 Integração Claude API', what: 'Automatizar a geração de relatórios técnicos personalizados.', todo: ['Criar conta na Anthropic (tier gratuito disponível)', 'Estudar quickstart: docs.anthropic.com (15 min)', 'Criar prompt template que gera relatório de eficiência a partir dos dados do dashboard', 'Botão "Gerar Relatório" no dashboard que chama a API', 'Output: texto técnico personalizado com recomendações'], resources: 'docs.anthropic.com, tier gratuito da API', criteria: 'Botão no dashboard que gera relatório técnico automático e personalizado.' },
  c2_5: { title: '📄 Deploy + GitHub', what: 'Publicar o dashboard online e o código no GitHub como portfólio.', todo: ['Deploy no Streamlit Cloud (gratuito)', 'Criar repositório no GitHub com README documentado', 'Ter pelo menos 5 repositórios técnicos limpos no GitHub total', 'Testar a URL pública — funciona sem instalar nada?'], resources: 'Streamlit Cloud, GitHub', criteria: 'URL pública acessível + repositório limpo no GitHub.' },
  c2_6: { title: '📝 Artigo Técnico LinkedIn/Medium', what: 'Publicar conteúdo para validar expertise e atrair prospects.', todo: ['Tema sugerido: "Como cervejarias perdem 20% de energia sem saber"', 'Incluir link para o dashboard funcional', 'Formato: problema → dados → sua análise → conclusão prática', '500-1000 palavras, linguagem acessível (dono de cervejaria tem que entender)', 'Publicar no LinkedIn como Article + versão no Medium para SEO'], resources: 'LinkedIn Publishing, Medium', criteria: '1 artigo publicado com link para dashboard.' },
  c3_1: { title: '👨‍🏫 Indicações de Professores', what: 'Usar sua rede UFMG enquanto ainda tem acesso. Quando sair, perde o título de "estudante" que abre portas.', todo: ['Conversar com 3 professores de termodinâmica/processos/energia', 'Pedir diretamente: "Professor, conhece alguma cervejaria ou usina que eu possa abordar?"', 'Mostrar o dashboard demo — construa credibilidade', 'Pedir feedback técnico no projeto', 'Professores podem gerar 1-3 indicações "quentes" — muito mais valiosas que cold outreach'], resources: 'Seus professores de termodinâmica, fenômenos de transporte, operações unitárias', criteria: '3 conversas realizadas, pelo menos 1 indicação obtida.' },
  c3_2: { title: '🔗 LinkedIn: 100 Conexões', what: 'Expandir rede com decisores do setor.', todo: ['Buscar: "gerente de produção cervejaria" ou "gerente industrial usina"', 'Buscar: "dono cervejaria artesanal" + MG', 'Enviar conexão com mensagem personalizada (NÃO genérica)', 'Postar 1 conteúdo técnico por semana (insights sobre eficiência)', '100 conexões enviadas com mensagem personalizada'], resources: 'LinkedIn, LinkedIn Sales Navigator (trial gratuito)', criteria: '100 conexões enviadas, 30+ aceitas.' },
  c3_3: { title: '📧 20 Cold E-mails', what: 'Primeiro lote de abordagens frias usando o script do plano.', todo: ['Usar o script de e-mail do plano (Seção 4.2 para cervejarias, 4.3 para usinas)', 'Personalizar cada e-mail com nome da empresa e dado específico', 'Instalar Mailtrack (extensão Chrome) para rastrear aberturas', 'Enviar 20 e-mails no total (mix cervejarias + usinas)', 'Follow-up em 5 dias se não respondeu, máximo 3 follow-ups', 'Rastrear tudo na planilha: data, canal, resposta, próximo passo', 'META: 50 abordagens para converter 1 diagnóstico (taxa 2-5%)'], resources: 'Gmail, Mailtrack, planilha de prospects', criteria: '20 e-mails enviados e rastreados na planilha.' },
  c3_4: { title: '🍺 Evento de Cervejarias', what: 'Networking presencial em evento do setor.', todo: ['Pesquisar próximos eventos: Festival Brasileiro da Cerveja, Mondial de la Bière BH, ACERVA Mineira', 'Preparar "elevator pitch" de 30 segundos sobre o que você faz', 'Levar pen drive com dashboard demo para mostrar na hora', 'Trocar 2-3 cartões/contatos', 'Follow-up em 48h com todos os contatos'], resources: 'ACERVA Mineira, Instagram de eventos cervejeiros em MG', criteria: 'Participação em 1 evento + follow-up em 48h.' },
  c3_5: { title: '🆓 3 Diagnósticos Gratuitos Oferecidos', what: 'A oferta irrecusável: diagnóstico energético gratuito com entrega tangível.', todo: ['Selecionar 3 cervejarias da planilha (mais receptivas ou com indicação)', 'Oferecer: "Preciso das 12 últimas contas de energia + 1h de conversa. Em 5 dias entrego relatório."', 'Deixar claro: sem compromisso, sem custo. Objetivo é construir portfólio.', 'Se perguntarem "quanto custa?": "O diagnóstico é gratuito. Se fizer sentido implementar, discutimos valores."', 'NUNCA venda na primeira conversa'], resources: 'Script da Seção 4.2 do plano, planilha de prospects', criteria: '3 propostas de diagnóstico gratuito enviadas formalmente.' },
  c3_6: { title: '🌐 Site Provisório', what: 'Presença online mínima para credibilidade.', todo: ['Criar página simples no Carrd.co ou Notion (1 hora de trabalho)', 'Incluir: quem é, o que faz, link para dashboard demo, contato', 'URL compartilhável para incluir nos e-mails e LinkedIn', 'Não precisa ser perfeito — precisa existir'], resources: 'Carrd.co (gratuito), Notion', criteria: 'URL pública com portfólio e contato.' },
  c3_7: { title: '✅ Checklist de Saída da Faculdade', what: 'Antes de receber o diploma, TODOS estes itens devem estar prontos.', todo: ['☐ MEI aberto e conta PJ ativa', '☐ Projeto demonstração funcional (dashboard + relatório automatizado)', '☐ 1 artigo publicado no LinkedIn ou Medium', '☐ Planilha de 80+ prospects (cervejarias + usinas) com contatos', '☐ 20+ cold outreaches realizados', '☐ 3+ conversas com professores pedindo indicações', '☐ Site provisório no ar', '☐ GitHub com 5+ repositórios técnicos (limpos e documentados)'], resources: 'Todas as tarefas anteriores', criteria: 'TODOS os 8 itens marcados. Sem exceção.' },
  c4_1: { title: '📧 10 E-mails Toda Segunda', what: 'Volume é a chave. Mínimo 50 abordagens para converter 1 diagnóstico.', todo: ['Lote de 10 e-mails toda segunda-feira, seguindo script da Seção 4', 'Personalizar cada um com nome e dado da empresa', 'Rastrear aberturas com Mailtrack', 'Atualizar planilha de prospects com status'], resources: 'Gmail, Mailtrack, planilha', criteria: 'Manter a rotina por 4 semanas consecutivas (40+ e-mails).' },
  c4_2: { title: '📞 5 Ligações Toda Terça', what: 'Ligação é mais efetiva que e-mail para cervejarias pequenas.', todo: ['Script: "Sou engenheiro químico, estou fazendo estudo de eficiência energética em cervejarias da região e gostaria de oferecer análise gratuita."', 'Pedir para falar com responsável de produção ou manutenção', 'Meta: 5 ligações, 2 conversas efetivas por semana', 'Anotar tudo na planilha'], resources: 'Script da Seção 4.4 do plano', criteria: '5 ligações/semana por 4 semanas (20+ ligações).' },
  c4_3: { title: '📱 LinkedIn Toda Quarta', what: 'Construir presença e autoridade online.', todo: ['1 post técnico por semana (insight sobre eficiência energética)', '20 novas conexões com mensagem personalizada', 'Comentar em posts de cervejeiros e gestores industriais', 'Compartilhar artigos relevantes com sua opinião técnica'], resources: 'LinkedIn', criteria: 'Manter por 4 semanas: 4 posts + 80 conexões.' },
  c4_4: { title: '🔄 Follow-up Toda Quinta', what: 'Quem não responde na primeira vez pode responder na segunda. Máximo 3 follow-ups.', todo: ['Revisar planilha: quem não respondeu nos últimos 5 dias?', 'Enviar follow-up gentil e breve', 'Após 3 follow-ups sem resposta: arquivar e partir para próximo', 'Nunca parecer desesperado — tom profissional sempre'], resources: 'Planilha de prospects', criteria: 'Follow-up sistemático por 4 semanas.' },
  c4_5: { title: '🚶 2 Visitas Presenciais Toda Sexta', what: 'Visita presencial é o canal mais efetivo para cervejarias locais de BH.', todo: ['Selecionar 2 cervejarias da planilha que ficam perto', 'Levar pen drive com dashboard demo', 'Não vender — oferecer o diagnóstico gratuito', 'Se o dono não estiver: deixar contato e pedir para agendar', 'Atualizar planilha com resultado da visita'], resources: 'Pen drive com demo, cartão de visita', criteria: '2 visitas/semana por 4 semanas (8+ visitas).' },
  c4_6: { title: '🎯 Primeiro Interesse em Diagnóstico', what: 'O momento mais importante: alguém aceitou seu diagnóstico gratuito.', todo: ['Pelo menos 1 cervejaria ou usina aceitou a oferta', 'Confirmar por e-mail o que será necessário (contas de energia, 1h de conversa)', 'Agendar data e horário para coleta de dados / visita'], resources: 'Sua persistência e volume de abordagens', criteria: '1 aceite formal para diagnóstico gratuito.' },
  c4_7: { title: '🏭 Visita Técnica e Coleta de Dados', what: 'Visitar presencialmente, coletar dados reais e entender o processo produtivo.', todo: ['Coletar 12 últimas contas de energia elétrica', 'Levantar perfil de produção (litros/mês ou tc/safra)', 'Identificar equipamentos: caldeira, câmara fria, envase, compressores', 'Fotografar instalações (com permissão)', 'Entender a rotina de produção: horários de pico, sazonalidade', 'Entregar relatório em 5 dias úteis (NÃO mais)'], resources: 'Checklist de visita técnica, câmera do celular, caderno de anotações', criteria: 'Visita realizada + dados de 12 meses coletados.' },
  c5_1: { title: '📊 Análise: Consumo vs. Benchmark', what: 'Comparar os dados reais do cliente com os benchmarks do setor.', todo: ['Tabular dados mensais de consumo (kWh) e produção (litros/tc)', 'Calcular consumo específico (kWh/litro ou kWh/tc)', 'Comparar com benchmark: cervejaria eficiente 8-12 kWh/hl, média 15-25 kWh/hl', 'Identificar sazonalidade e tendências', 'Mapear consumo por sistema: refrigeração, aquecimento, envase, iluminação'], resources: 'Dados coletados na visita, benchmarks EPE/PROCEL', criteria: 'Análise de dados completa com gráficos comparativos.' },
  c5_2: { title: '💡 3 Oportunidades de Redução por ROI', what: 'Identificar e priorizar as oportunidades de economia de energia.', todo: ['Listar todas as oportunidades identificadas na análise', 'Para cada: estimar investimento necessário e economia anual em R$', 'Calcular ROI e payback para cada oportunidade', 'Ranquear por: viabilidade × impacto econômico', 'Top 3: as mais rápidas de implementar com maior retorno', 'Fórmula: Preço do projeto = 10-15% da economia anual estimada'], resources: 'Dados da análise, referências de custo de equipamentos', criteria: '3 oportunidades quantificadas com ROI e payback.' },
  c5_3: { title: '📋 Relatório Profissional + Dashboard', what: 'Transformar o diagnóstico gratuito em material que impressione e convença.', todo: ['Relatório de 8-15 páginas com: capa profissional, sumário executivo, análise detalhada, gráficos, recomendações', 'Dashboard interativo personalizado com dados do cliente', 'Incluir: consumo atual vs. benchmark, 3 oportunidades com ROI, estimativa R$/ano de economia', 'Usar template de relatório profissional (Canva ou LaTeX)', 'Revisar 2x antes de entregar — zero erros'], resources: 'Canva para design, Dashboard Streamlit, dados analisados', criteria: 'Relatório completo e dashboard personalizado prontos para apresentação.' },
  c5_4: { title: '🤝 Apresentação Presencial', what: 'Apresentar o relatório pessoalmente. NUNCA enviar por e-mail sem fazer a reunião.', todo: ['Agendar reunião presencial com o decision maker', 'Levar relatório impresso + notebook com dashboard', 'Apresentar os findings de forma visual e objetiva', 'Focar nos R$ — "sua cervejaria pode economizar R$ X/ano"', 'No final, oferecer: "Posso implementar a oportunidade #1 com acompanhamento por 3 meses"', 'Se pedir preço: usar fórmula 10-15% da economia anual estimada'], resources: 'Relatório impresso, dashboard no notebook, proposta comercial preparada', criteria: 'Reunião presencial realizada com apresentação completa.' },
  c5_5: { title: '💰 Proposta de Projeto Pago', what: 'Converter o diagnóstico gratuito em projeto pago de implementação.', todo: ['Preparar proposta formal: escopo, entregáveis, prazo, preço', 'Opção A: Preço fixo (R$ 3.000-8.000 para cervejaria)', 'Opção B: Success fee (15-20% da economia comprovada no 1º ano)', 'Nunca cobrar por hora nos primeiros projetos', 'Se não pode pagar R$ 8.000: oferecer pacote menor de R$ 3.000 com escopo reduzido', 'Proposta → aprovação → início → execução → case study'], resources: 'Template de proposta comercial', criteria: 'Proposta formal enviada ao cliente após reunião.' },
  c5_6: { title: '🔄 Pivot se Necessário', what: 'Se cervejarias não converteram, pivotar para segmentos adjacentes.', todo: ['Se 20+ diagnósticos gratuitos e 0 projetos pagos: problema é segmento ou preço', 'Segmentos alternativos com mesma lógica térmica:', '• Padarias industriais — alto consumo de fornos e refrigeração, donos acessíveis', '• Laticínios de pequeno porte — refrigeração intensiva', '• Frigoríficos — cadeia de frio é ~60% do custo energético', '• Fábricas de alimentos em BH e região', 'Adaptar o dashboard e pitch para o novo segmento'], resources: 'Seção 9.2 do plano — Segmentos Alternativos', criteria: 'Decisão tomada: escalar ou pivotar, baseada em dados.' },
  c6_1: { title: '🎉 Primeiro Projeto Pago', what: 'O marco mais importante. Qualquer valor conta — o primeiro real faturado muda tudo.', todo: ['Executar o projeto com qualidade máxima', 'Documentar TUDO para portfólio (fotos, dados, resultados)', 'Overdeliver: entregar mais do que prometeu', 'Manter comunicação constante com o cliente durante a execução', 'Ao final: relatório de resultados + plano de manutenção'], resources: 'Todas as ferramentas e skills desenvolvidas', criteria: 'Projeto executado + payment received. Qualquer valor.' },
  c6_2: { title: '📝 Case Study Documentado', what: 'Transformar o primeiro projeto em material de venda para os próximos.', todo: ['Estrutura: Problema → Abordagem → Resultado → Valor entregue', 'Incluir dados reais (anonimizados se necessário)', 'Formato: 1-2 páginas, visual limpo, números destacados', 'Publicar versão resumida no LinkedIn', 'Usar como prova nas próximas propostas'], resources: 'Canva para design, dados do projeto', criteria: 'Case study publicado no LinkedIn e disponível para enviar a prospects.' },
  c6_3: { title: '⭐ Depoimento do Cliente', what: 'Pedir depoimento escrito — vale ouro para credibilidade.', todo: ['Pedir ao cliente um parágrafo sobre: o que você fez, como foi trabalhar com você, resultado obtido', 'Formato ideal: nome, cargo, empresa + texto de 3-5 linhas', 'Publicar no LinkedIn (com permissão do cliente)', 'Incluir no site e nas próximas propostas'], resources: 'Seu relacionamento com o primeiro cliente', criteria: 'Depoimento escrito recebido e publicado.' },
  c6_4: { title: '💰 R$ 5.000/mês', what: 'Cobrir custos pessoais e provar sustentabilidade — equiparar salário júnior CLT.', todo: ['Pode ser: 1 projeto de R$ 5k OU 2 de R$ 2.5k OU mix projeto + recorrência', 'Preço tabelado (após 2+ cases): R$ 3.000-8.000/cervejaria, R$ 8.000-20.000/usina', 'Se preciso: complementar com freelance de dados (Workana/99freelas R$ 50-150/hr)', 'Marco esperado: Mês 6-8 (Dez/2026-Fev/2027)'], resources: 'Pipeline de prospects, portfólio com cases', criteria: 'R$ 5.000+ faturados em um único mês.' },
  c6_5: { title: '🔄 Pacote de Monitoramento Recorrente', what: 'Criar receita recorrente com clientes existentes — previsibilidade financeira.', todo: ['Oferecer para clientes que implementaram: monitoramento mensal de indicadores', 'Cervejaria: R$ 800-2.000/mês', 'Usina: R$ 2.000-5.000/mês', 'Entregável mensal: dashboard atualizado + relatório de performance', 'Meta: 2-3 clientes em recorrência = base mínima garantida'], resources: 'Dashboard automatizado, dados do cliente', criteria: 'Pelo menos 1 cliente em modelo de recorrência mensal.' },
  c6_6: { title: '👥 3+ Clientes Ativos', what: 'Diversificação e prova de que o modelo funciona.', todo: ['Manter pipeline: sempre ter 2-3 prospects em negociação', 'Mix ideal: cervejarias (volume) + usinas (ticket maior)', 'Quando demanda > capacidade: considerar contratar estagiário (R$ 1.200-1.800/mês)', 'Cada cliente novo: case study + depoimento'], resources: 'Pipeline contínuo, portfólio crescente', criteria: '3 clientes pagantes ativos simultaneamente.' },
  c6_7: { title: '🏆 R$ 10.000/mês por 3 Meses', what: 'O marco de sustentabilidade real. Se atingir: você tem um negócio.', todo: ['R$ 10.000/mês por 3 meses consecutivos = negócio viável', 'Neste ponto: considerar contratar estagiário de engenharia', 'Investir em automação (mais IA, menos trabalho manual)', 'Se ao mês 12 não atingiu: considerar emprego CLT + consultoria no horário livre', 'O que levar se não der certo: portfólio de dados, skill de vendas, rede de contatos, conhecimento de IA — tudo vale ouro no mercado CLT'], resources: 'Sua persistência, pipeline e portfólio', criteria: 'R$ 10.000+ faturados por mês, 3 meses seguidos.' },
};
