const TASK_DETAILS = {
  t1_1: {
    title: '📖 Fundamentos de Mecânica dos Fluidos',
    what: 'Estudar os conceitos fundamentais de hidráulica industrial que formam a base de toda análise de sistemas de bombeamento.',
    todo: [
      'Estudar a equação de Bernoulli e conservação de energia em sistemas de tubulação',
      'Dominar perdas de carga por Darcy-Weisbach e dimensionamento de tubos',
      'Entender curvas de bomba, curvas de sistema e ponto de operação',
      'Calcular NPSH disponível vs. NPSH requerido com margem de segurança',
      'Estudar mecanismos de cavitação e estratégias de prevenção',
      'Comparar bombas centrífugas vs. deslocamento positivo',
      'Entender configurações série vs. paralelo',
    ],
    resources: 'API 610, Hydraulic Institute Standards, Perry\'s Chemical Engineers\' Handbook (Cap. 6)',
    criteria: 'Consiga resolver pelo menos 5 problemas de cálculo hidráulico manualmente, incluindo dimensionamento de tubulação e análise de NPSH.',
  },
  t1_2: {
    title: '📖 Normas Industriais e Interpretação de Diagramas',
    what: 'Familiarizar-se com os padrões da indústria e a linguagem visual de plantas de processo.',
    todo: [
      'Estudar API 610 — Bombas Centrífugas para Indústria de Petróleo',
      'Aprender a interpretar Piping and Instrumentation Diagrams (P&ID)',
      'Praticar leitura e construção de Process Flow Diagrams (PFD)',
      'Estudar data sheets de equipamentos e curvas de performance',
      'Conhecer modos de falha comuns: cavitação, falha de selo, desgaste de impeller',
      'Entender instrumentação básica: medidores de vazão, transmissores de pressão',
      'Estudar fundamentos de dimensionamento de válvulas de controle',
    ],
    resources: 'API 610, ISA Standards, exemplos de P&IDs industriais reais',
    criteria: 'Consiga ler um P&ID de um sistema de bombeamento e identificar todos os instrumentos, válvulas e equipamentos.',
  },
  t1_3: {
    title: '🔧 Relatório Diagnóstico de Sistema Hidráulico',
    what: 'Desenvolver uma análise hidráulica completa para um cenário industrial real ou hipotético — sistema de água de resfriamento, transferência de crude ou estação de bombeamento.',
    todo: [
      'Selecionar cenário: planta química, refinaria ou tratamento de água',
      'Calcular vazão em toda a rede de tubulação usando Darcy-Weisbach',
      'Dimensionar todos os segmentos com fatores de atrito apropriados',
      'Calcular queda de pressão por segmento e resistência total do sistema',
      'Fazer seleção de bomba e análise de performance',
      'Plotar curva do sistema e sobrepor curva do fabricante',
      'Identificar ponto de operação e comparar com condições de projeto',
      'Simular bloqueio parcial: como o ponto de operação muda?',
      'Simular impeller desgastado (15% redução de head): análise de impacto',
      'Simular início de cavitação: sinais de alerta e ações corretivas',
    ],
    resources: 'Dados de catálogos de bombas (KSB, Sulzer, Grundfos), tabelas de rugosidade de tubos',
    criteria: 'Entregar relatório de 8-12 páginas com cálculos, gráficos de curvas e conclusões técnicas.',
  },
  t1_4: {
    title: '🤖 Calculadora Interativa de Pump System',
    what: 'Usar IA (Claude, ChatGPT ou Cursor) como co-desenvolvedor para construir uma calculadora de sistema de bombeamento baseada em browser ou planilha.',
    todo: [
      'Criar campos de entrada: diâmetro, comprimento, rugosidade, propriedades do fluido, elevação, vazão',
      'Calcular automaticamente: número de Reynolds, fator de atrito (Moody), velocity head, pontos da curva do sistema',
      'Plotar curva do sistema a partir dos inputs do usuário',
      'Criar tabela de comparação de bombas: inputar múltiplas bombas e identificar a melhor',
      'Implementar checker de NPSH: alertar risco de cavitação baseado nas condições de sucção',
      'Gerar exportação para PDF: relatório de uma página com resumo automático',
    ],
    resources: 'Usar prompts como: "Build me a Python/Streamlit app that calculates pipe system pressure drop using Darcy-Weisbach"',
    criteria: 'Ferramenta funcional que um cliente possa testar com seus próprios dados. Publicar online (Streamlit Cloud, GitHub Pages, etc).',
  },
  t1_5: {
    title: '🌋 Cenário: Bomba Petroquímica com -20% Vazão',
    what: 'Resolver um caso real: planta petroquímica reporta que bombas de transferência de crude entregam 15-20% menos vazão que o projetado. Equipe de operação suspeita defeito nas bombas.',
    todo: [
      'Analisar com seu modelo hidráulico e identificar as causas reais',
      'Descobrir: (1) duas válvulas de controle calibradas incorretamente gerando resistência extra',
      'Descobrir: (2) um segmento de tubo com depósitos de incrustação aumentando rugosidade',
      'Descobrir: (3) desgaste menor no impeller, mas dentro da tolerância',
      'Concluir: a curva do SISTEMA mudou — as bombas estão performando corretamente na SUA curva',
      'Demonstrar o valor: economizar $80,000-$120,000 em substituição desnecessária de bombas',
    ],
    resources: 'Use os dados do seu projeto da tarefa 1.3 como base',
    criteria: 'Produzir uma análise de 2-3 páginas com diagnóstico, evidências numéricas e recomendações priorizadas.',
  },
  t1_6: {
    title: '📄 Entregável Completo da Fase 1',
    what: 'Compilar todos os produtos da Fase 1 em um portfólio profissional apresentável.',
    todo: [
      'Pump System Diagnostic Calculator — web app ou Excel com backend Python/VBA',
      'Sample Hydraulic Analysis Report — 8-12 páginas com cálculos, plots e conclusões',
      'Pump Selection Matrix — ferramenta de comparação para 3-5 bombas candidatas',
      'NPSH Checklist — guia de avaliação de campo de 1 página para risco de cavitação',
      'Glossário de Modos de Falha Hidráulica — documento de referência para comunicação com cliente',
    ],
    resources: 'Formatar tudo como se fosse entregue a um cliente real: capa profissional, sumário executivo, cálculos detalhados em apêndice.',
    criteria: 'Todos os 5 itens prontos, formatados profissionalmente e publicados no seu portfólio (GitHub, site pessoal, etc).',
  },
  t1_7: {
    title: '💼 Primeira Proposta no Upwork',
    what: 'Entrar no mercado freelance internacional com sua primeira proposta real.',
    todo: [
      'Criar perfil no Upwork com título otimizado: "Chemical Engineer | Pump Systems | Process Safety | Industrial Data Analysis"',
      'Criar perfil no Kolabtree com 2 serviços de consultoria a preços fixos',
      'Criar perfil no Workana (forte em mercados da América Latina)',
      'Buscar jobs com 0-10 propostas (maior probabilidade de ganhar)',
      'Oferecer sample gratuito: "Calculo um segmento de tubo com seus dados antes de compromisso"',
      'Usar sua calculadora como demonstração viva nas propostas',
      'Referenciar normas específicas (API 610, Hydraulic Institute) nas propostas',
      'Jobs-alvo: "Pump sizing calculation" ($50-$300), "Review hydraulic design" ($80-$250)',
    ],
    resources: 'Upwork, Kolabtree, Workana, Freelancer.com',
    criteria: 'Pelo menos 3 propostas enviadas em plataformas diferentes. Não precisa ganhar o job — o objetivo é ENVIAR.',
  },
  t1_8: {
    title: '🤖 Ponte Financeira: Scale AI / Outlier AI',
    what: 'Estabelecer a primeira fonte de renda em dólar para substituir sua bolsa de estágio com rapidez.',
    todo: [
      'Atualizar LinkedIn destacando conhecimento em Engenharia (Cálculo, Termodinâmica, Python)',
      'Criar Currículo (CV) em inglês focado em STEM (descartar a linguagem de estagiário genérico)',
      'Cadastrar na Outlier AI focado em projetos STEM / Math / Chemistry Expert',
      'Cadastrar na DataAnnotation Tech',
      'Passar nos testes admissionais provando fluência em inglês e rigor técnico',
      'Regra inquebrável: Não usar ChatGPT ou Claude para responder as avaliações (eles banem na hora)'
    ],
    resources: 'Guia: plano_outlier_ai.md e prompt_posicionamento_linkedin.md',
    criteria: 'Aprovação recebida (onboarding concluído) e pagamento do primeiro task sacado.',
  },
  t2_1: {
    title: '📖 Fundamentos de Balanço de Massa e Energia',
    what: 'Dominar os princípios de conservação aplicados a sistemas industriais.',
    todo: [
      'Princípios de conservação: sistemas steady-state e transientes',
      'Análise de grau de liberdade para sistemas de processo',
      'Problemas de balanço multi-unidade (reciclo, bypass, purga)',
      'Tie components e reagentes limitantes',
      'Balanços de entalpia: calor sensível, calor latente, calor de reação',
      'Tabelas de vapor e dados de propriedades de refrigerantes',
      'Efetividade de trocadores de calor e método NTU',
      'Balanço material em destilação (McCabe-Thiele básico)',
      'Equações de reator: CSTR, PFR, batch',
    ],
    resources: 'Felder & Rousseau, Perry\'s Handbook, Steam Tables',
    criteria: 'Resolver 5+ problemas de balanço de massa com reciclo e purga.',
  },
  t2_2: {
    title: '📖 Otimização e KPIs de Processo',
    what: 'Aprender a medir e melhorar a eficiência de processos industriais.',
    todo: [
      'KPIs de processo e métricas de rendimento',
      'Pinch analysis para oportunidades de integração térmica',
      'Identificação de gargalos em sistemas de produção',
      'Controle estatístico de processo (SPC): cartas de controle',
      'Estratégias de debottlenecking e utilização de capacidade',
      'Métricas de eficiência energética: consumo específico de energia',
      'Fundamentos de simulação (conceitos Aspen, HYSYS)',
      'Avaliação econômica: análise de custo operacional',
      'Benchmarking de utilidades vs. padrões da indústria',
    ],
    resources: 'Linnhoff (Pinch Analysis), Turton (Analysis & Design of Chemical Processes)',
    criteria: 'Saber calcular eficiência energética, identificar pelo menos 3 oportunidades de otimização em um cenário dado.',
  },
  t2_3: {
    title: '🔧 Auditoria Completa de Utilidades de Planta',
    what: 'Realizar auditoria de processo completa para cenário industrial (farmacêutico, alimentos ou petroquímica).',
    todo: [
      'Fechamento completo de balanço de massa no contorno do processo',
      'Balanço de energia com breakdown de utilidades: vapor, água de resfriamento, eletricidade, gás',
      'Análise de rendimento: eficiência de matéria-prima e pontos de perda',
      'Benchmarking: comparar valores reais vs. best practice da indústria',
      'Identificação de oportunidades: listar 5-10 otimizações específicas com savings estimados',
      'Matriz de priorização: ranquear por viabilidade e impacto econômico',
    ],
    resources: 'DOE Best Practices for Steam Systems, dados de benchmark da indústria',
    criteria: 'Relatório de 15-20 páginas com análise completa e recomendações quantificadas.',
  },
  t2_4: {
    title: '🤖 Dashboard de Auditoria de Processos',
    what: 'Construir ferramenta interativa de auditoria com assistência de IA.',
    todo: [
      'Calculadora de balanço de massa: inputar dados de correntes, fechar balanço e reportar perdas',
      'Tracker de intensidade energética: calcular energia específica (kWh por unidade de produto)',
      'Scorecard de oportunidades: ranking ponderado de oportunidades de otimização',
      'Comparação de benchmark: plotar sua instalação vs. valores de referência da indústria',
      'Sumário executivo auto-gerado: IA escreve draft de seção de relatório a partir dos inputs',
      'Detector de anomalias: alertar correntes onde erro de fechamento excede ±2%',
    ],
    resources: 'Python/Streamlit ou React, Claude API para geração de texto',
    criteria: 'Dashboard funcional que aceite upload de dados e gere visualizações e relatório automaticamente.',
  },
  t2_5: {
    title: '🌋 Cenário: Auditoria de Vapor — Planta de Alimentos',
    what: 'Analisar 6 meses de dados de utilidades e produção de uma planta de processamento de alimentos com custos energéticos altos.',
    todo: [
      'Construir balanços de massa e energia do sistema de geração e distribuição de vapor',
      'Identificar: falhas em purgadores causando 18% de perda de vapor',
      'Identificar: fouling em trocador do pasteurizador aumentando demanda de vapor em 12%',
      'Identificar: falha na bomba de retorno de condensado — 35% do condensado não está sendo recuperado',
      'Recomendar: programa de auditoria e substituição de purgadores (ROI < 6 meses)',
      'Recomendar: limpeza programada do HEX do pasteurizador',
      'Quantificar: savings projetados de $45,000-$85,000/ano com investimento total < $15,000',
    ],
    resources: 'Use dados simulados ou datasets públicos de utilidades industriais',
    criteria: 'Análise com números reais ou simulados demonstrando ROI claro para cada recomendação.',
  },
  t2_6: {
    title: '📄 Entregável Completo da Fase 2',
    what: 'Compilar artefatos da Fase 2.',
    todo: [
      'Process Audit Dashboard — ferramenta interativa com inputs de balanço e findings automáticos',
      'Sample Process Audit Report — 15-20 páginas com análise completa',
      'Utility Benchmarking Template — scorecard comparativo vs. referências industriais',
      'Optimization Opportunity Register — template para log e ranking de oportunidades',
      'One-page Executive Summary Template — para comunicação com C-suite',
    ],
    resources: 'Formatar tudo como entrega a cliente real.',
    criteria: 'Todos os 5 itens prontos e no portfólio.',
  },
  t2_7: {
    title: '💼 Primeiro Projeto Pago ($50-$200)',
    what: 'Fechar e completar seu primeiro projeto pago como freelancer técnico.',
    todo: [
      'Aplicar para jobs no Upwork na faixa de $50-$200',
      'Oferecer preço 30-40% abaixo do mercado nos primeiros 3 jobs em troca de reviews detalhadas',
      'Jobs-alvo: "Mass and energy balance for chemical process" ($200-$800)',
      'Jobs-alvo: "Excel spreadsheet for engineering calculations" ($30-$150)',
      'Usar suas ferramentas como demonstração viva nas propostas',
      'Registrar no Scale AI / Outlier AI como avaliador técnico ($15-$25/hr) como renda imediata',
      'ENTREGAR o projeto com qualidade, pedir review escrita do cliente',
    ],
    resources: 'Upwork, Kolabtree, Workana, Scale AI, Outlier AI',
    criteria: 'Pelo menos 1 projeto pago CONCLUÍDO com payment received. Qualquer valor conta.',
  },
  t3_1: {
    title: '📖 Metodologia HAZOP',
    what: 'Dominar a metodologia de estudo HAZOP conforme os padrões CCPS.',
    todo: [
      'Estrutura do HAZOP: nós, guide words, desvios',
      'Guide words: NO / LESS / MORE / REVERSE / OTHER THAN / AS WELL AS / PART OF',
      'Framework causa-consequência-salvaguarda',
      'Camadas de Proteção Independentes (IPLs)',
      'Documentação HAZOP: worksheets e tracking de ações',
      'Matriz de risco e ranking (metodologia CCPS)',
      'Distinção entre causa credível vs. evento iniciador',
      'Critérios de avaliação de salvaguardas existentes',
      'Papéis: líder de HAZOP vs. participante',
      'Desvios comuns e suas causas típicas em plantas químicas',
    ],
    resources: 'CCPS Guidelines for HAZOP Studies, IChemE HAZOP Guide',
    criteria: 'Conseguir conduzir uma análise de desvio completa para um nó de processo dado.',
  },
  t3_2: {
    title: '📖 Gestão de Risco e Frameworks Regulatórios',
    what: 'Entender os fundamentos de gestão de risco e os frameworks regulatórios internacionais.',
    todo: [
      'Critérios de tolerância a risco CCPS e matrizes de risco',
      'Fundamentos de Layer of Protection Analysis (LOPA)',
      'Árvore de eventos e árvore de falhas (básico)',
      'Categorias de severidade de consequência (CCPS)',
      'Estimativa de frequência de eventos iniciadores',
      'Conceito de Risk Reduction Factor (RRF)',
      'Visão geral de Safety Integrity Level (SIL) — IEC 61511',
      'Distinção BPCS vs. SIS',
      'Hierarquia de Inherently Safer Design (ISD)',
      'Requisitos de Process Safety Information (PSI) — PSM/SEVESO',
    ],
    resources: 'CCPS Risk Based Process Safety, OSHA PSM Standard, EU SEVESO III Directive',
    criteria: 'Conseguir preencher uma matriz de risco 5x5 e classificar cenários corretamente.',
  },
  t3_3: {
    title: '🔧 Estudo HAZOP — Sistema de Alimentação de Reator',
    what: 'Conduzir um estudo HAZOP formal em um nó de processo definido com controle de fluxo, temperatura e proteção de pressão.',
    todo: [
      'Definir nó com limites claros e design intent',
      'Analisar mínimo 5 desvios de guide word por nó',
      'Análise completa causa-consequência-salvaguarda para cada desvio',
      'Ranking de risco usando matriz 5x5 (severidade x probabilidade)',
      'Action items para cada nível de risco inaceitável',
      'Tabela resumo HAZOP: hazards principais, níveis de risco e recomendações',
    ],
    resources: 'Template CCPS, P&ID de exemplo de sistema de reator',
    criteria: 'HAZOP worksheet completa com pelo menos 3 nós e 15+ desvios analisados.',
  },
  t3_4: {
    title: '🤖 Gerador de Planilha HAZOP + Risk Screener',
    what: 'Construir ferramenta assistida por IA para suporte a estudos HAZOP.',
    todo: [
      'Formulário de input de nó: descrever nó, condições operacionais e equipamentos',
      'Gerador de desvios assistido por IA: usar Claude API para sugerir causas para cada guide word',
      'Calculadora de matriz de risco: matriz 5x5 interativa com atribuição automática de nível',
      'Checker de salvaguardas: inputar salvaguardas existentes, ferramenta avalia adequação',
      'Tracker de ações: gerar log de ações formatado com responsáveis e datas',
      'Exportador de relatório HAZOP: produzir documento Word ou PDF com worksheet completa',
    ],
    resources: 'Claude API, python-docx ou jsPDF para exportação',
    criteria: 'Ferramenta funcional que gere worksheet HAZOP a partir de inputs e exporte relatório.',
  },
  t3_5: {
    title: '🌋 Cenário: PSSR — Unidade de Recuperação de Solvente Modificada',
    what: 'Conduzir HAZOP screening em unidade modificada para novo produto com flash point diferente.',
    todo: [
      'HAZOP screening de 3 nós: feed de coluna, condensador de recovery, interface com tanque',
      'Identificar: novo solvente tem flash point menor — flame arrester pode estar subdimensionado',
      'Identificar: controle de temperatura no preheater sem trip de alta no novo range',
      'Identificar: documentação da nova química do processo está incompleta',
      'Entregar: PSSR checklist, HAZOP summary com 4 ações críticas',
      'Recomendar: hold no startup até resolução de 2 itens críticos',
    ],
    resources: 'Templates PSSR, dados de flash point de solventes comuns',
    criteria: 'Relatório de screening com checklist completa e recomendação fundamentada de startup hold.',
  },
  t3_6: {
    title: '📄 Entregável Completo da Fase 3',
    what: 'Portfólio de segurança de processos.',
    todo: [
      'HAZOP Worksheet Template — alinhado com CCPS, pronto para uso industrial',
      'Risk Matrix Tool — planilha 5x5 customizável com auto-color coding',
      'HAZOP Screening Report — relatório de 20 páginas para cenário definido',
      'Process Hazard Checklist — ferramenta de screening rápido para hazards comuns',
      'IPL Evaluation Criteria Reference Card — referência rápida para adequação de salvaguardas',
    ],
    resources: 'Formatar como entrega a cliente real.',
    criteria: 'Todos os 5 itens prontos e publicados.',
  },
  t3_7: {
    title: '💼 2 Propostas de Segurança Enviadas',
    what: 'Entrar no mercado de consultoria de segurança de processos.',
    todo: [
      'Buscar no Upwork: "HAZOP review and risk assessment" ($300-$1,500)',
      'Buscar no Kolabtree: "Chemical process safety consultant" ($500-$2,000)',
      'LinkedIn outreach: contatar HSE Managers e Process Safety Engineers',
      'Oferecer template HAZOP gratuito para firmas EPC, depois propor serviços de review',
      'Enviar pelo menos 2 propostas formais em plataformas diferentes',
    ],
    resources: 'Upwork, Kolabtree, LinkedIn Sales Navigator',
    criteria: '2 propostas enviadas com linguagem técnica adequada e uso do portfólio como prova.',
  },
  t4_1: { title: '📖 LOPA & SIL', what: 'Estudar quantificação de risco e integridade funcional de segurança.', todo: ['LOPA: quantificação de risco baseada em cenários', 'Frequências de eventos iniciadores — CCPS / OREDA', 'Critérios de tolerância e severidade', 'Valores de crédito de IPLs independentes', 'Modificadores condicionais: probabilidade de ignição, ocupação', 'Estrutura e documentação de worksheet LOPA', 'Determinação de SIL a partir de resultados LOPA', 'Design de SIF conforme IEC 61511', 'Conceitos de arquitetura SIS', 'Intervalos de proof test e cobertura diagnóstica'], resources: 'IEC 61511, CCPS LOPA Guidelines, OREDA Handbook', criteria: 'Preencher worksheet LOPA completo para 3 cenários com determinação SIL.' },
  t4_2: { title: '📖 Investigação de Incidentes & BPCS', what: 'Métodos de investigação e proteção por controle.', todo: ['Root cause analysis: 5-Why, Bow-Tie, CCPS PIRT', 'Investigação de incidentes — requisitos OSHA PSM', 'Operating envelope e Management of Change (MOC)', 'Fundamentos de alarm management — EEMUA 191', 'BPCS reliability e common cause failures', 'Documentação e teste de interlocks', 'Métricas de process safety: lagging vs. leading indicators', 'Frameworks regulatórios: OSHA PSM, EU SEVESO III, API RP 750'], resources: 'CSB Investigation Reports, CCPS Process Safety Leading Metrics', criteria: 'Completar investigação de incidente real (CSB report) usando 5-Why e Bow-Tie.' },
  t4_3: { title: '🔧 LOPA + Investigação de Incidente', what: 'Selecionar finding de alto risco da Fase 3 e desenvolver LOPA completo + análise de incidente documentado.', todo: ['LOPA: definir cenário, evento iniciador, consequência e target de risco tolerável', 'Identificar e creditar IPLs com taxas de demanda CCPS', 'Calcular RRF requerido e atribuir SIL se SIF necessário', 'Investigação: analisar incidente documentado (CSB, ARIA)', 'Aplicar 5-Why e Bow-Tie para identificar root causes', 'Desenvolver relatório de lições aprendidas'], resources: 'CSB videos, ARIA database, CCPS LOPA examples', criteria: 'LOPA report + investigation report completos e fundamentados.' },
  t4_4: { title: '🤖 Calculadora LOPA + Banco de Lições', what: 'Ferramenta de cálculo LOPA automatizado com módulo de lições aprendidas.', todo: ['LOPA worksheet com cálculo automático de RRF e SIL', 'Biblioteca de IPLs pré-carregada com taxas de falha CCPS', 'Análise de gap de risco: comparar redução atual vs. requerida', 'Módulo de lições: formulário estruturado para detalhes de incidentes', 'Análise de tendências: agregar incidentes para padrões sistêmicos', 'Dashboard executivo de risco: resumo visual de riscos abertos e SILs'], resources: 'Python/Streamlit ou Excel avançado', criteria: 'Ferramenta funcional com IPL library e geração automática de resultado SIL.' },
  t4_5: { title: '🌋 Cenário: SIL Assessment — Tanque Atmosférico', what: 'Avaliação SIL para proteção de sobrepressão em terminal de armazenamento de petróleo.', todo: ['Eventos iniciadores: falha de válvula (fails-open), alto fluxo upstream, outlet bloqueado', 'Consequência: falha do casco, release de hidrocarboneto, potencial fogo/explosão', 'Creditar IPLs: controlador de nível, alarme, resposta do operador, PSV', 'Resultado: gap requer SIL 1 SIF (PSV com backup SIS shutoff)', 'Entregar: LOPA report, especificação SIL 1, recomendações de arquitetura SIS'], resources: 'API 2350, IEC 61511', criteria: 'Documentação completa para revisão de segurador e regulador.' },
  t4_6: { title: '📄 Entregável Completo da Fase 4', what: 'Portfólio de safety avançado.', todo: ['LOPA Calculator Tool', 'Sample LOPA Report completo', 'Incident Investigation Template (5-Why + Bow-Tie)', 'Process Safety Metrics Dashboard', 'SIL/SIF Specification Template per IEC 61511'], resources: 'Formatar profissionalmente.', criteria: 'Todos os 5 itens no portfólio.' },
  t4_7: { title: '💼 Primeiro Artigo no LinkedIn', what: 'Publicar conteúdo técnico para posicionamento como especialista.', todo: ['Escrever artigo de 500-1000 palavras sobre tema técnico', 'Sugestões: "Why Pump Cavitation Costs More Than You Think" ou "HAZOP vs. What-If: When to Use Each"', 'Formato: problema real → análise técnica → lição prática', 'Incluir 1-2 imagens/diagramas técnicos', 'Publicar no LinkedIn como article (não post)', 'Compartilhar em grupos de engenharia relevantes'], resources: 'LinkedIn Publishing, Canva para diagramas', criteria: 'Artigo publicado com pelo menos 10 engajamentos (likes/comments).' },
  t5_1: { title: '📖 Dados Industriais & Estatística', what: 'Fundamentos de análise de dados de processo.', todo: ['Características de séries temporais em plantas de processo', 'Sistemas de data historian: OSIsoft PI, Aspen InfoPlus.21', 'SPC: Shewhart charts, CUSUM, EWMA', 'Índices de capabilidade: Cp, Cpk', 'Métodos de detecção de outliers: Z-score, IQR, isolation forest', 'Monitoramento estatístico multivariado (MSPM) básico', 'Validação de sensores e qualidade de dados', 'Pré-processamento: missing values, normalização'], resources: 'Montgomery (Statistical Quality Control), Python pandas/numpy docs', criteria: 'Implementar SPC charts e detecção de outliers em dataset real.' },
  t5_2: { title: '📖 ML para Engenharia de Processos', what: 'Machine learning aplicado a dados industriais.', todo: ['Modelos de regressão para predição de processo', 'Anomaly detection: supervised vs. unsupervised', 'Feature engineering para variáveis de processo', 'Decision trees para classificação de falhas', 'PCA para monitoramento de processo', 'Racionalização de alarmes', 'Fundamentos de digital twin', 'Validação de modelo e incerteza', 'Explainability em modelos de ML industriais'], resources: 'scikit-learn docs, Tennessee Eastman Process dataset', criteria: 'Treinar pelo menos 2 modelos diferentes em dados industriais com métricas de validação.' },
  t5_3: { title: '🔧 Sistema de Detecção de Anomalias', what: 'Construir e validar sistema de detecção usando dataset público industrial.', todo: ['Exploração de dados: visualizar variáveis-chave, identificar problemas de qualidade', 'Feature engineering: ratios, rolling statistics, lag variables', 'Modelo baseline: Z-score e IQR-based anomaly flags', 'Modelo avançado: isolation forest ou one-class SVM', 'Validação: precision, recall e false positive rate', 'Priorização de alertas: ranking por severidade e frequência', 'Dashboard: visualizar timeline de anomalias com contexto'], resources: 'Tennessee Eastman Process, Steel Plate Faults dataset', criteria: 'Modelo funcional com precisão > 80% e documentação do approach.' },
  t5_4: { title: '🤖 Dashboard de Monitoramento de Planta', what: 'Dashboard interativo para análise de dados de processo.', todo: ['Upload de dados CSV de historian export', 'Auto-cálculo de KPIs: eficiência, rendimento, tendências de consumo', 'Timeline de anomalias: flags com severidade e timestamp', 'Explorador de correlação: IA identifica variáveis correlacionadas com KPI selecionado', 'Interpretação em linguagem natural: IA escreve resumo do estado da planta', 'Comparação de benchmark: esta semana vs. melhor semana registrada', 'Geração de relatório: one-click weekly performance report'], resources: 'Python/Streamlit, plotly, Claude API', criteria: 'Dashboard que aceite CSV e gere análise automatizada com visualizações.' },
  t5_5: { title: '🌋 Cenário: Early Warning de Compressor', what: 'Planta de gás com shutdowns recorrentes custando $150k-$300k cada. 12 meses de dados disponíveis.', todo: ['Construir modelo usando vibração, temperatura, pressão sucção/descarga e potência', 'Identificar padrão precursor: aumento lento de temperatura + mudança de tendência de vibração 2-5 dias antes', 'Resultado: early warning 3-7 dias antes de falha prevista', 'Demonstrar valor: mesmo 1 shutdown evitado paga meses de consultoria'], resources: 'Datasets públicos de manutenção preditiva', criteria: 'Modelo que detecte degradação com antecedência de pelo menos 48h.' },
  t5_6: { title: '📄 Entregável da Fase 5', what: 'Portfólio de data analytics.', todo: ['Anomaly Detection Demo com documentação', 'Plant Performance Dashboard funcional', 'Process Data Analysis Report', 'Alarm Rationalization Template', 'Predictive Maintenance Case Study end-to-end'], resources: 'Formatar profissionalmente.', criteria: 'Todos os 5 itens no portfólio.' },
  t5_7: { title: '💼 2 Projetos de Análise de Dados', what: 'Completar projetos pagos de data analytics.', todo: ['Upwork: "Analyze plant historian data and identify inefficiencies" ($400-$2,000)', 'Upwork: "Build Python dashboard for process monitoring" ($300-$1,500)', 'Kolabtree: "Data scientist with process background for industrial IoT" ($75-$150/hr)', 'LinkedIn: contatar Digital Transformation Leads', 'Outlier AI / Scale AI: data labeling industrial ($20-$45/hr)', 'Completar e ENTREGAR 2 projetos com payment received'], resources: 'Upwork, Kolabtree, Scale AI', criteria: '2 projetos pagos concluídos com reviews positivas.' },
  t6_1: { title: '📖 Integração e Troubleshooting Avançado', what: 'Competências avançadas de consultoria técnica.', todo: ['Metodologia sistemática de troubleshooting de processo', 'Protocolos de avaliação de condição de equipamento', 'Otimização sob restrições operacionais', 'Frameworks de priorização multi-hazard', 'Avaliação de qualidade de procedimentos operacionais', 'Avaliação de processo de MOC', 'Indicadores de cultura de process safety', 'Otimização de turnaround e inspeção', 'Gap analysis regulatório (PSM, SEVESO, ISO)', 'Análise de lifecycle cost de equipamentos'], resources: 'CCPS Guidelines, API inspection codes, ISO 45001', criteria: 'Capacidade de conduzir troubleshooting sistemático em cenário dado.' },
  t6_2: { title: '📖 Business & Consulting Skills', what: 'Habilidades de negócio para consultoria independente.', todo: ['Estruturar engajamento: escopo, entregáveis, fees', 'Escrever propostas técnicas e Statement of Work (SoW)', 'Client relationship management', 'Retainer vs. project-based pricing', 'Considerações fiscais e legais internacionais', 'Construção de marca técnica: LinkedIn, escrita, speaking', 'Pricing de serviços de engenharia internacionalmente', 'Gestão de scope creep e expectativas'], resources: 'Consulting Success (livro), Million Dollar Consulting (Alan Weiss)', criteria: 'Conseguir escrever SoW e proposta completas para um engajamento hipotético.' },
  t6_3: { title: '🔧 Capstone: Review Integrado para Planta Química', what: 'Projeto final — pacote completo de consultoria para planta real/hipotética preparando para auditoria regulatória.', todo: ['Process Engineering Review: hidráulica, balanços, condição de equipamentos', 'Safety Risk Screening: gaps HAZOP, requisitos LOPA, status SIL/SIF', 'Data Analysis: tendência de KPIs 6 meses com resumo de anomalias', 'Recommendations Register: plano de ação priorizado com custos e projeções', 'Executive Summary: resumo de 2 páginas para C-suite com business case'], resources: 'Usar TODAS as ferramentas construídas ao longo do roadmap', criteria: 'Relatório de 40+ páginas — flagship portfolio piece.' },
  t6_4: { title: '🤖 Plataforma Integrada de Consultoria', what: 'Protótipo funcional do seu toolset de consultoria.', todo: ['Client project intake form com coleta estruturada', 'Integração multi-domínio: conectar módulos hidráulico, M&E, safety e data', 'Aggregador automático de findings em risk register unificado', 'Engine de priorização: ranking por impacto, risco e custo', 'Gerador de relatório branded com sua marca e dados do cliente', 'Conceito de client portal para compartilhar findings'], resources: 'Todas as ferramentas anteriores integradas', criteria: 'Plataforma funcional que demonstre capacidade de consultoria end-to-end.' },
  t6_5: { title: '🌋 Cenário: Engajamento Completo — Pharma 200 Funcionários', what: 'Simular engajamento de consultoria completo para fabricante farmacêutico preparando para auditoria PSM.', todo: ['Semana 1: revisão de dados, balanços, data sheets de equipamentos', 'Semana 2: gap analysis HAZOP, LOPA screening top 5, review de documentação SIS', 'Semana 3: análise de dados, benchmarking KPI, redação de relatório', 'Site visit: entrevistas com operadores, inspeção física, validação de findings', 'Fee total: $8,000-$15,000 para 3 semanas — renda transformacional'], resources: 'Usar o cenário como case study detalhado', criteria: 'Pacote completo: proposta, SoW, relatório 40p, apresentação executiva, plano de ação.' },
  t6_6: { title: '📄 Entregável Final Completo', what: 'Portfólio profissional completo de consultoria.', todo: ['Complete Consulting Engagement Package — proposta, SoW, template, relatório', 'Integrated Engineering Platform Demo funcional', 'Company Brochure / Services Overview — documento de 2 páginas', 'LinkedIn Profile otimizado com thought leadership', 'Pricing Guide interno para escopar e precificar engajamentos', 'Client Testimonial Strategy documentada'], resources: 'Canva para brochure, LinkedIn para perfil', criteria: 'Todos os 6 itens finalizados e publicados.' },
  t6_7: { title: '💼 Toptal + Outreach Direto', what: 'Lançamento no mercado como consultor de verdade.', todo: ['Aplicar no Toptal como Chemical Engineering consultant ($100-$200/hr)', 'Publicar 2 artigos técnicos por mês no LinkedIn', 'Direct outreach: empresas industriais em mercados emergentes (BR, CO, MX, IN, SEA)', 'Partnership com firmas de engenharia locais como remote specialist', 'Considerar: apresentações em conferências (ISChE, AIChE, SBQ)', 'Considerar: desenvolvimento de curso gravado sobre HAZOP ou pump troubleshooting'], resources: 'Toptal, LinkedIn Sales Navigator, Industry Associations', criteria: 'Aplicação Toptal enviada + pelo menos 5 outreach diretos para empresas.' },
};
